# """
# Background analysis tasks — run asynchronously in Celery workers.

# Observability changes (M6):
#   - structlog replaces plain logging.getLogger → every log line is JSON
#   - correlation_id / task_id / doc_id bound via structlog.contextvars so
#     ALL lines from one task share the same IDs (traceable in Azure Log Analytics)
#   - analysis_started / analysis_completed / analysis_failed update the
#     in-memory metrics store that /api/metrics reads
#   - Canonical completion log:
#       log.info("analysis_complete",
#                doc_id=..., ai=..., web=..., orig=..., internal=...,
#                sources=..., duration_s=..., case=...)
# """

# import asyncio
# import uuid
# from datetime import datetime
# from typing import List, Optional

# import structlog

# from app.core.celery_client import celery_app
# # from app.core.metrics import analysis_started, analysis_completed, analysis_failed
# from app.libs.database import db_service
# from app.libs.extract import extract_text
# from app.libs.google_search import google_search_with_matches
# from app.libs.ai_detection import detect_ai_content_detailed
# from app.libs.plagiarism import (
#     local_plagiarism_score,
#     local_plagiarism_score_with_commoncrawl,
# )
# from app.libs.models import AnalysisResult

# # ── Logging setup — runs once when the Celery worker imports this module ───────
# # configure_logging() initialises structlog + stdlib root handler with JSON output.
# # This call is safe even if main.py already called it (idempotent handler swap).
# # from app.libs.logger import configure_logging, get_logger

# # configure_logging()
# # log = get_logger("tasks")

# # ── Configuration (same as main.py) ───────────────────────────────────────────
# MIN_TEXT_LENGTH = 20
# SEARCH_TEXT_WORD_LIMIT = 300


# # ── Helpers (duplicated from main.py to keep workers self-contained) ──────────

# def encode_web_source(url: str, match_pct: Optional[float] = None) -> str:
#     """Encode a web source URL (with optional match%) as a DB-safe string."""
#     if match_pct is not None:
#         return f"web::{url}::{round(match_pct, 2)}"
#     return f"web::{url}"


# def compute_scores(
#     verbatim_web_score: float,
#     commoncrawl_score: float,
#     local_score: float,
#     ai_score: float,
# ):
#     """Compute final scores from raw analysis signals."""
#     plagiarism = max(verbatim_web_score, commoncrawl_score * 0.5)
#     plagiarism = round(min(100.0, max(0.0, plagiarism)), 2)
#     originality = round(max(0.0, 100.0 - plagiarism), 2)
#     ai = round(min(100.0, max(0.0, ai_score)), 2)
#     internal = round(min(100.0, max(0.0, local_score)), 2)
#     return plagiarism, originality, ai, internal


# def classify_submission(ai_pct: float, plagiarism_pct: float) -> dict:
#     """Map (AI%, Plagiarism%) to interpretation case."""
#     ai_high = ai_pct >= 70
#     ai_med = 40 <= ai_pct < 70
#     plag_high = plagiarism_pct >= 60
#     plag_med = 20 <= plagiarism_pct < 60

#     if ai_high and plag_high:
#         return {
#             "case": "Case 3 — AI Generated & Plagiarized",
#             "verdict": "AI-Generated AND Plagiarized",
#             "description": (
#                 "Strong AI authorship signals combined with high verbatim web similarity. "
#                 "High probability this was generated by an AI tool using source "
#                 "material it was trained on or directly accessed."
#             ),
#             "risk": "critical",
#             "action": "Reject. Request original human-authored work with proper citations.",
#         }

#     if not ai_high and plag_high:
#         return {
#             "case": "Case 1 — Human Plagiarism",
#             "verdict": "Human Plagiarism Detected",
#             "description": (
#                 "Low AI probability with high verbatim web similarity. "
#                 "Content appears manually copied or paraphrased from existing "
#                 "sources without proper attribution."
#             ),
#             "risk": "high",
#             "action": "Reject. Request original work with citations for all borrowed content.",
#         }

#     if ai_high and not plag_high and not plag_med:
#         return {
#             "case": "Case 2 — AI Generated (Original)",
#             "verdict": "AI-Generated Content — Not Copied",
#             "description": (
#                 "High AI authorship probability. Content does not match known web "
#                 "sources — this appears to be original AI output, not copied from "
#                 "existing material."
#             ),
#             "risk": "high",
#             "action": "Review per institution AI policy. Original content but likely not student's own work.",
#         }

#     if not ai_high and not ai_med and not plag_high and not plag_med:
#         return {
#             "case": "Case 4 — Human Original",
#             "verdict": "Likely Original Human Work",
#             "description": (
#                 "Low AI probability and low verbatim web similarity. "
#                 "Content appears to be original human-authored work with no "
#                 "significant plagiarism concerns."
#             ),
#             "risk": "low",
#             "action": "Accept. No significant concerns detected.",
#         }

#     if ai_med and not plag_high:
#         return {
#             "case": "Case 5 — Possible AI Assistance",
#             "verdict": "Possible AI Assistance Detected",
#             "description": (
#                 "Moderate AI signals detected. Content may have been drafted or "
#                 "edited with AI assistance. Verbatim web plagiarism is not significant."
#             ),
#             "risk": "medium",
#             "action": (
#                 "Request student to confirm authorship. "
#                 "May be acceptable if institution permits AI assistance with disclosure."
#             ),
#         }

#     if plag_med:
#         return {
#             "case": "Case 6 — Moderate Similarity",
#             "verdict": f"Moderate Web Similarity{' + Possible AI Assistance' if ai_med else ''}",
#             "description": (
#                 f"Moderate verbatim overlap with web sources"
#                 f"{' with possible AI assistance' if ai_med else ''}. "
#                 "Common in research-heavy work; review matched sources to confirm "
#                 "adequate citation of borrowed content."
#             ),
#             "risk": "medium",
#             "action": "Review matched sources. Verify all borrowed content is properly cited.",
#         }

#     return {
#         "case": "Inconclusive",
#         "verdict": "Manual Review Recommended",
#         "description": "Mixed signals detected. Automated classification is inconclusive.",
#         "risk": "medium",
#         "action": "A human reviewer should assess this submission.",
#     }


# # ── Core async logic ───────────────────────────────────────────────────────────

# async def _run_analysis_async(document_id: int, user_id: str, task_self):
#     """
#     ✅ ASYNC CORE LOGIC — separated from Celery task decorator.
#     This allows proper async/await handling without event loop issues.

#     Observability:
#       - structlog.contextvars carries task_id + doc_id on every log line
#       - Timing captured at each stage and reported in the canonical completion log
#       - Metrics counters updated via analysis_started / analysis_completed / analysis_failed
#     """
#     import time as _time

#     # ── Bind task-scoped context so every log line carries these fields ────────
#     structlog.contextvars.bind_contextvars(
#         task_id=task_self.request.id,
#         doc_id=document_id,
#         user_id=user_id,
#     )

#     log.info("analysis_task_started", stage="load_document")
#     task_self.update_state(state="PROGRESS", meta={"progress": 10, "stage": "Loading document"})

#     # ── Load document ──────────────────────────────────────────────────────────
#     t_start = _time.perf_counter()

#     doc = await db_service.get_document(document_id)
#     if not doc:
#         raise ValueError(f"Document {document_id} not found")

#     if doc["user_id"] != user_id:
#         raise PermissionError(f"User {user_id} not authorized for document {document_id}")

#     text = doc.get("extracted_text", "") or ""
#     if len(text.strip()) < MIN_TEXT_LENGTH:
#         raise ValueError(f"Insufficient text extracted ({len(text)} chars)")

#     start = datetime.utcnow()

#     # ── 1. INTERNAL DB SIMILARITY (20%) ───────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 20, "stage": "Checking internal DB"})
#     t1 = _time.perf_counter()

#     others = await db_service.get_all_documents_texts(exclude_id=document_id)
#     other_texts: List[str] = [
#         (d.get("extracted_text") or d.get("text") or "")
#         for d in others
#         if (d.get("extracted_text") or d.get("text") or "").strip()
#     ]

#     local_score = 0.0
#     try:
#         local_score = await local_plagiarism_score(text, other_texts)
#         log.info(
#             "internal_db_similarity_done",
#             internal_score=round(local_score, 1),
#             compared_docs=len(other_texts),
#             stage_ms=round((_time.perf_counter() - t1) * 1000, 1),
#         )
#     except Exception as e:
#         log.exception("internal_db_similarity_failed", error=str(e))

#     # ── 2. VERBATIM WEB SEARCH (40%) ──────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 40, "stage": "Searching web"})
#     t2 = _time.perf_counter()

#     verbatim_web_score = 0.0
#     web_search_result = {
#         "urls": [],
#         "matches": {},
#         "top_match_pct": 0.0,
#         "queries_used": [],
#     }

#     search_text = " ".join(text.split()[:SEARCH_TEXT_WORD_LIMIT])

#     try:
#         web_search_result = google_search_with_matches(search_text)
#         verbatim_web_score = web_search_result.get("top_match_pct", 0.0)
#         found_urls = web_search_result.get("urls", [])
#         log.info(
#             "web_search_done",
#             urls_found=len(found_urls),
#             top_match_pct=round(verbatim_web_score, 1),
#             stage_ms=round((_time.perf_counter() - t2) * 1000, 1),
#         )
#     except Exception as e:
#         log.exception("web_search_failed", error=str(e))

#     # ── 3. COMMONCRAWL (50%) ──────────────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 50, "stage": "Checking CommonCrawl"})
#     t3 = _time.perf_counter()

#     commoncrawl_score = 0.0
#     try:
#         commoncrawl_score = local_plagiarism_score_with_commoncrawl(text)
#         log.info(
#             "commoncrawl_done",
#             score=round(commoncrawl_score, 1),
#             stage_ms=round((_time.perf_counter() - t3) * 1000, 1),
#         )
#     except Exception as e:
#         log.warning("commoncrawl_failed", error=str(e))

#     # ── 4. AI DETECTION (70%) ─────────────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 70, "stage": "Detecting AI"})
#     t4 = _time.perf_counter()

#     ai_score_raw = 0.0
#     ai_detail = {}
#     try:
#         ai_detail = detect_ai_content_detailed(text)
#         ai_score_raw = float(ai_detail.get("score", 0.0))
#         ai_score_raw = min(100.0, max(0.0, ai_score_raw))
#         log.info(
#             "ai_detection_done",
#             ai_score=round(ai_score_raw, 1),
#             is_academic=ai_detail.get("is_academic", False),
#             stage_ms=round((_time.perf_counter() - t4) * 1000, 1),
#         )
#     except Exception as e:
#         log.exception("ai_detection_failed", error=str(e))

#     # ── 5. COMPUTE SCORES (80%) ───────────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 80, "stage": "Computing scores"})

#     plagiarism_score, originality_score, ai_score, internal_score = compute_scores(
#         verbatim_web_score=verbatim_web_score,
#         commoncrawl_score=commoncrawl_score,
#         local_score=local_score,
#         ai_score=ai_score_raw,
#     )

#     interpretation = classify_submission(ai_score, plagiarism_score)

#     # ── 6. BUILD SOURCES LIST (90%) ───────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 90, "stage": "Finalizing results"})

#     sources: List[str] = []
#     found_urls = web_search_result.get("urls", [])
#     url_matches = web_search_result.get("matches", {})

#     for url in found_urls:
#         m = url_matches.get(url, {})
#         match_pct = m.get("match_pct")
#         sources.append(encode_web_source(url, match_pct))

#     if local_score > 15:
#         sources.append(f"local_db::document:{document_id}")

#     sources = list(dict.fromkeys(sources))  # Deduplicate

#     end = datetime.utcnow()
#     processing_time = (end - start).total_seconds()

#     # ── 7. STORE RESULT (95%) ─────────────────────────────────────────────────
#     result = AnalysisResult(
#         document_id=document_id,
#         analyzed_by=user_id,
#         ai_detected_percentage=ai_score,
#         web_source_percentage=plagiarism_score,
#         local_similarity_percentage=internal_score,
#         human_written_percentage=originality_score,
#         analysis_summary=interpretation["verdict"],
#         analysis_date=end,
#         matched_web_sources=sources,
#         processing_time_seconds=processing_time,
#     )

#     await db_service.create_analysis_result(result)

#     # ── Canonical completion log (queryable in Azure Log Analytics) ───────────
#     log.info(
#         "analysis_complete",
#         doc_id=document_id,
#         ai=ai_score,
#         web=plagiarism_score,
#         orig=originality_score,
#         internal=internal_score,
#         sources=len(sources),
#         duration_s=round(processing_time, 2),
#         case=interpretation["case"],
#         risk=interpretation["risk"],
#     )

#     task_self.update_state(state="SUCCESS", meta={"progress": 100, "stage": "Complete"})

#     return {
#         "document_id": document_id,
#         "status": "completed",
#         "scores": {
#             "ai": ai_score,
#             "plagiarism": plagiarism_score,
#             "originality": originality_score,
#             "internal": internal_score,
#         },
#         "processing_time": processing_time,
#     }


# # ── Celery task wrapper ────────────────────────────────────────────────────────

# @celery_app.task(bind=True, name="run_analysis")
# def run_analysis(self, document_id: int, user_id: str):
#     """
#     Celery task wrapper — handles async execution cleanly.

#     Lifecycle hooks:
#       analysis_started()   → increments active counter in metrics store
#       analysis_completed() → decrements active, increments done, records duration
#       analysis_failed()    → decrements active, increments error counter
#     """
#     analysis_started()
#     try:
#         result = asyncio.run(_run_analysis_async(document_id, user_id, self))
#         analysis_completed(result.get("processing_time", 0.0))
#         return result

#     except Exception as e:
#         analysis_failed()
#         log.exception(
#             "analysis_task_failed",
#             task_id=self.request.id,
#             doc_id=document_id,
#             error=str(e),
#         )
#         self.update_state(
#             state="FAILURE",
#             meta={
#                 "progress": 0,
#                 "error": str(e),
#             },
#         )
#         raise
#     finally:
#         # Always clear contextvars so the next task on this worker starts clean
#         structlog.contextvars.clear_contextvars()











































# """
# Background analysis tasks — run asynchronously in Celery workers.

# BUGS FIXED IN THIS VERSION
# ───────────────────────────────────────────────────────────────────────
# BUG 1 (CRITICAL — NameError crash):
#     analysis_started() / analysis_completed() / analysis_failed()
#     were called at lines 382/385/389 but their import was commented out.
#     FIX: Replaced with lightweight inline counter functions using a
#          module-level dict. No external metrics module needed.

# BUG 2 (CRITICAL — NameError crash):
#     'log' variable was never defined. configure_logging() and
#     get_logger() were both commented out, leaving 'log' undefined.
#     Every log.info() call crashed the worker with NameError.
#     FIX: Replaced structlog with standard logging.getLogger("tasks").
#          All log.xxx() calls changed to logger.xxx().

# BUG 3 (CRITICAL — TypeError crash):
#     local_plagiarism_score() is a SYNCHRONOUS function in plagiarism.py.
#     It was called with 'await' inside _run_analysis_async().
#     'await' on a non-coroutine raises TypeError.
#     FIX: Removed 'await'. CPU-intensive sync call wrapped with
#          asyncio.to_thread() so it doesn't block the event loop.

# BUG 4 (HIGH — Frontend Network Error):
#     The frontend polls /analysis-status/{document_id} (old endpoint).
#     The new async flow returns a task_id from /analyze/{document_id}.
#     Frontend never got task_id because it was using the old endpoint.
#     FIX: /analysis-status now queries Celery + DB so both old and
#          new frontends work. task_id stored in DB via update_task_id().

# BUG 5 (HIGH — Sync functions blocking async loop):
#     google_search_with_matches() and detect_ai_content_detailed()
#     are synchronous blocking functions called inside async context.
#     FIX: Both wrapped with asyncio.to_thread() to run in thread pool.
# ───────────────────────────────────────────────────────────────────────
# """

# import asyncio
# import logging
# from datetime import datetime
# from typing import List, Optional

# from app.core.celery_client import celery_app
# from app.libs.database import db_service
# from app.libs.google_search import google_search_with_matches
# from app.libs.ai_detection import detect_ai_content_detailed
# from app.libs.plagiarism import (
#     local_plagiarism_score,
#     local_plagiarism_score_with_commoncrawl,
# )
# from app.libs.models import AnalysisResult

# # ── Standard logger — replaces the broken structlog setup ─────────────────────
# # BUG 2 FIX: 'log' was never defined because configure_logging/get_logger
# # were commented out. Using standard logging instead — no extra package needed.
# logger = logging.getLogger("tasks")

# # ── Configuration ──────────────────────────────────────────────────────────────
# MIN_TEXT_LENGTH        = 20
# SEARCH_TEXT_WORD_LIMIT = 300


# # ── Lightweight metrics stubs ──────────────────────────────────────────────────
# # BUG 1 FIX: analysis_started / analysis_completed / analysis_failed were
# # imported from app.core.metrics but that import was commented out, leaving
# # the functions undefined. Simple module-level counters replace them.
# # These can be swapped for real metrics (Prometheus, Datadog) later.

# _metrics = {"active": 0, "completed": 0, "failed": 0}


# def analysis_started() -> None:
#     _metrics["active"] += 1
#     logger.info("Metrics | active=%d completed=%d failed=%d",
#                 _metrics["active"], _metrics["completed"], _metrics["failed"])


# def analysis_completed(duration_s: float = 0.0) -> None:
#     _metrics["active"]    = max(0, _metrics["active"] - 1)
#     _metrics["completed"] += 1
#     logger.info("Metrics | active=%d completed=%d failed=%d | duration=%.1fs",
#                 _metrics["active"], _metrics["completed"], _metrics["failed"], duration_s)


# def analysis_failed() -> None:
#     _metrics["active"] = max(0, _metrics["active"] - 1)
#     _metrics["failed"] += 1
#     logger.warning("Metrics | active=%d completed=%d failed=%d",
#                    _metrics["active"], _metrics["completed"], _metrics["failed"])


# # ── Source encoding helpers (self-contained — no main.py dependency) ──────────

# def encode_web_source(url: str, match_pct: Optional[float] = None) -> str:
#     """Encode a web URL + optional verbatim match% as a DB-safe string."""
#     if match_pct is not None:
#         return f"web::{url}::{round(match_pct, 2)}"
#     return f"web::{url}"


# # ── Score computation (mirrors main.py) ───────────────────────────────────────

# def compute_scores(
#     verbatim_web_score: float,
#     commoncrawl_score:  float,
#     local_score:        float,
#     ai_score:           float,
# ):
#     """Compute final four report metrics from raw signals."""
#     plagiarism  = max(verbatim_web_score, commoncrawl_score * 0.5)
#     plagiarism  = round(min(100.0, max(0.0, plagiarism)), 2)
#     originality = round(max(0.0, 100.0 - plagiarism), 2)
#     ai          = round(min(100.0, max(0.0, ai_score)), 2)
#     internal    = round(min(100.0, max(0.0, local_score)), 2)
#     return plagiarism, originality, ai, internal


# # ── Interpretation matrix (mirrors main.py) ────────────────────────────────────

# def classify_submission(ai_pct: float, plagiarism_pct: float) -> dict:
#     """Map (AI%, Plagiarism%) → interpretation case."""
#     ai_high   = ai_pct >= 70
#     ai_med    = 40 <= ai_pct < 70
#     plag_high = plagiarism_pct >= 60
#     plag_med  = 20 <= plagiarism_pct < 60

#     if ai_high and plag_high:
#         return {
#             "case":        "Case 3 — AI Generated & Plagiarized",
#             "verdict":     "AI-Generated AND Plagiarized",
#             "description": (
#                 "Strong AI authorship signals combined with high verbatim web similarity. "
#                 "High probability this was generated by an AI tool using source "
#                 "material it was trained on or directly accessed."
#             ),
#             "risk":   "critical",
#             "action": "Reject. Request original human-authored work with proper citations.",
#         }

#     if not ai_high and plag_high:
#         return {
#             "case":        "Case 1 — Human Plagiarism",
#             "verdict":     "Human Plagiarism Detected",
#             "description": (
#                 "Low AI probability with high verbatim web similarity. "
#                 "Content appears manually copied or paraphrased from existing "
#                 "sources without proper attribution."
#             ),
#             "risk":   "high",
#             "action": "Reject. Request original work with citations for all borrowed content.",
#         }

#     if ai_high and not plag_high and not plag_med:
#         return {
#             "case":        "Case 2 — AI Generated (Original)",
#             "verdict":     "AI-Generated Content — Not Copied",
#             "description": (
#                 "High AI authorship probability. Content does not match known web "
#                 "sources — this appears to be original AI output, not copied from "
#                 "existing material."
#             ),
#             "risk":   "high",
#             "action": "Review per institution AI policy. Original content but likely not student's own work.",
#         }

#     if not ai_high and not ai_med and not plag_high and not plag_med:
#         return {
#             "case":        "Case 4 — Human Original",
#             "verdict":     "Likely Original Human Work",
#             "description": (
#                 "Low AI probability and low verbatim web similarity. "
#                 "Content appears to be original human-authored work with no "
#                 "significant plagiarism concerns."
#             ),
#             "risk":   "low",
#             "action": "Accept. No significant concerns detected.",
#         }

#     if ai_med and not plag_high:
#         return {
#             "case":        "Case 5 — Possible AI Assistance",
#             "verdict":     "Possible AI Assistance Detected",
#             "description": (
#                 "Moderate AI signals detected. Content may have been drafted or "
#                 "edited with AI assistance. Verbatim web plagiarism is not significant."
#             ),
#             "risk":   "medium",
#             "action": (
#                 "Request student to confirm authorship. "
#                 "May be acceptable if institution permits AI assistance with disclosure."
#             ),
#         }

#     if plag_med:
#         return {
#             "case":        "Case 6 — Moderate Similarity",
#             "verdict":     f"Moderate Web Similarity{' + Possible AI Assistance' if ai_med else ''}",
#             "description": (
#                 f"Moderate verbatim overlap with web sources"
#                 f"{' with possible AI assistance' if ai_med else ''}. "
#                 "Common in research-heavy work; review matched sources to confirm "
#                 "adequate citation of borrowed content."
#             ),
#             "risk":   "medium",
#             "action": "Review matched sources. Verify all borrowed content is properly cited.",
#         }

#     return {
#         "case":        "Inconclusive",
#         "verdict":     "Manual Review Recommended",
#         "description": "Mixed signals detected. Automated classification is inconclusive.",
#         "risk":        "medium",
#         "action":      "A human reviewer should assess this submission.",
#     }


# # ── Core async analysis logic ──────────────────────────────────────────────────

# async def _run_analysis_async(document_id: int, user_id: str, task_self) -> dict:
#     """
#     Full analysis pipeline running inside asyncio.run().
#     All CPU-intensive sync functions are offloaded to a thread pool via
#     asyncio.to_thread() so they don't block the event loop.

#     BUG 3 FIX: local_plagiarism_score is SYNC — removed 'await'.
#     BUG 5 FIX: google_search_with_matches and detect_ai_content_detailed
#                are SYNC blocking — wrapped with asyncio.to_thread().
#     """
#     import time as _time

#     logger.info("[doc=%d] analysis_task_started", document_id)
#     task_self.update_state(state="PROGRESS", meta={"progress": 10, "stage": "Loading document"})

#     t_start = _time.perf_counter()

#     # ── Load document ──────────────────────────────────────────────────────────
#     doc = await db_service.get_document(document_id)
#     if not doc:
#         raise ValueError(f"Document {document_id} not found in database")

#     if doc["user_id"] != user_id:
#         raise PermissionError(f"User {user_id} is not authorized for document {document_id}")

#     text = doc.get("extracted_text", "") or ""
#     if len(text.strip()) < MIN_TEXT_LENGTH:
#         raise ValueError(
#             f"Insufficient text extracted from document {document_id} "
#             f"({len(text)} chars — minimum is {MIN_TEXT_LENGTH})"
#         )

#     start = datetime.utcnow()

#     # ── STAGE 1: Internal DB Similarity (20%) ─────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 20, "stage": "Checking internal database"})
#     t1 = _time.perf_counter()

#     others = await db_service.get_all_documents_texts(exclude_id=document_id)
#     other_texts: List[str] = [
#         (d.get("extracted_text") or d.get("text") or "")
#         for d in others
#         if (d.get("extracted_text") or d.get("text") or "").strip()
#     ]

#     local_score = 0.0
#     try:
#         # BUG 3 FIX: local_plagiarism_score is SYNC — no await, run in thread
#         local_score = await asyncio.to_thread(local_plagiarism_score, text, other_texts)
#         logger.info(
#             "[doc=%d] internal_db_similarity=%.1f%% compared_docs=%d elapsed_ms=%.0f",
#             document_id, local_score, len(other_texts),
#             (_time.perf_counter() - t1) * 1000,
#         )
#     except Exception as e:
#         logger.exception("[doc=%d] internal_db_similarity_failed: %s", document_id, e)

#     # ── STAGE 2: Verbatim Web Search (40%) ────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 40, "stage": "Searching web sources"})
#     t2 = _time.perf_counter()

#     verbatim_web_score = 0.0
#     web_search_result  = {"urls": [], "matches": {}, "top_match_pct": 0.0, "queries_used": []}
#     search_text        = " ".join(text.split()[:SEARCH_TEXT_WORD_LIMIT])

#     try:
#         # BUG 5 FIX: google_search_with_matches is SYNC — run in thread pool
#         web_search_result  = await asyncio.to_thread(google_search_with_matches, search_text)
#         verbatim_web_score = web_search_result.get("top_match_pct", 0.0)
#         found_urls         = web_search_result.get("urls", [])
#         logger.info(
#             "[doc=%d] web_search done | urls=%d top_match=%.1f%% queries=%d elapsed_ms=%.0f",
#             document_id, len(found_urls), verbatim_web_score,
#             len(web_search_result.get("queries_used", [])),
#             (_time.perf_counter() - t2) * 1000,
#         )
#     except Exception as e:
#         logger.exception("[doc=%d] web_search_failed: %s", document_id, e)

#     # ── STAGE 3: CommonCrawl (50%) ────────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 50, "stage": "Checking CommonCrawl"})
#     t3 = _time.perf_counter()

#     commoncrawl_score = 0.0
#     try:
#         commoncrawl_score = await asyncio.to_thread(
#             local_plagiarism_score_with_commoncrawl, text
#         )
#         logger.info(
#             "[doc=%d] commoncrawl=%.1f%% elapsed_ms=%.0f",
#             document_id, commoncrawl_score, (_time.perf_counter() - t3) * 1000,
#         )
#     except Exception as e:
#         logger.warning("[doc=%d] commoncrawl_failed: %s", document_id, e)

#     # ── STAGE 4: AI Detection (70%) ───────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 70, "stage": "Detecting AI content"})
#     t4 = _time.perf_counter()

#     ai_score_raw = 0.0
#     ai_detail    = {}
#     try:
#         # BUG 5 FIX: detect_ai_content_detailed is SYNC — run in thread pool
#         ai_detail    = await asyncio.to_thread(detect_ai_content_detailed, text)
#         ai_score_raw = float(ai_detail.get("score", 0.0))
#         ai_score_raw = min(100.0, max(0.0, ai_score_raw))
#         logger.info(
#             "[doc=%d] ai_detection=%.1f%% academic=%s likely_model=%s "
#             "breakdown: roberta=%.0f%% ppl=%.0f%% burst=%.0f%% "
#             "style=%.0f%% tokdist=%.0f%% patterns=%.0f%% elapsed_ms=%.0f",
#             document_id,
#             ai_score_raw,
#             ai_detail.get("is_academic", False),
#             ai_detail.get("likely_model") or "unknown",
#             ai_detail.get("breakdown", {}).get("roberta", 0),
#             ai_detail.get("breakdown", {}).get("perplexity", 0),
#             ai_detail.get("breakdown", {}).get("burstiness", 0),
#             ai_detail.get("breakdown", {}).get("stylometrics", 0),
#             ai_detail.get("breakdown", {}).get("token_dist", 0),
#             ai_detail.get("breakdown", {}).get("ai_patterns", 0),
#             (_time.perf_counter() - t4) * 1000,
#         )
#     except Exception as e:
#         logger.exception("[doc=%d] ai_detection_failed: %s", document_id, e)

#     # ── STAGE 5: Compute Scores (80%) ─────────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 80, "stage": "Computing final scores"})

#     plagiarism_score, originality_score, ai_score, internal_score = compute_scores(
#         verbatim_web_score = verbatim_web_score,
#         commoncrawl_score  = commoncrawl_score,
#         local_score        = local_score,
#         ai_score           = ai_score_raw,
#     )

#     interpretation = classify_submission(ai_score, plagiarism_score)

#     # ── STAGE 6: Build Sources List (90%) ─────────────────────────────────────
#     task_self.update_state(state="PROGRESS", meta={"progress": 90, "stage": "Finalizing results"})

#     sources:    List[str] = []
#     found_urls  = web_search_result.get("urls", [])
#     url_matches = web_search_result.get("matches", {})

#     for url in found_urls:
#         m         = url_matches.get(url, {})
#         match_pct = m.get("match_pct")
#         sources.append(encode_web_source(url, match_pct))

#     if local_score > 15:
#         sources.append(f"local_db::document:{document_id}")

#     sources = list(dict.fromkeys(sources))  # Deduplicate, preserve order

#     end             = datetime.utcnow()
#     processing_time = (end - start).total_seconds()

#     # ── STAGE 7: Store Result in DB (95%) ─────────────────────────────────────
#     result = AnalysisResult(
#         document_id                 = document_id,
#         analyzed_by                 = user_id,
#         ai_detected_percentage      = ai_score,
#         web_source_percentage       = plagiarism_score,
#         local_similarity_percentage = internal_score,
#         human_written_percentage    = originality_score,
#         analysis_summary            = interpretation["verdict"],
#         analysis_date               = end,
#         matched_web_sources         = sources,
#         processing_time_seconds     = processing_time,
#     )

#     await db_service.create_analysis_result(result)

#     logger.info(
#         "[doc=%d] analysis_complete | case=%s risk=%s "
#         "ai=%.1f%% plagiarism=%.1f%% originality=%.1f%% internal=%.1f%% "
#         "sources=%d duration=%.2fs",
#         document_id,
#         interpretation["case"],
#         interpretation["risk"],
#         ai_score, plagiarism_score, originality_score, internal_score,
#         len(sources), processing_time,
#     )

#     task_self.update_state(state="SUCCESS", meta={"progress": 100, "stage": "Complete"})

#     return {
#         "document_id": document_id,
#         "status":      "completed",
#         "scores": {
#             "ai":          ai_score,
#             "plagiarism":  plagiarism_score,
#             "originality": originality_score,
#             "internal":    internal_score,
#         },
#         "processing_time": processing_time,
#     }


# # ── Celery task wrapper ────────────────────────────────────────────────────────

# @celery_app.task(bind=True, name="run_analysis")
# def run_analysis(self, document_id: int, user_id: str):
#     """
#     Celery task — wraps async pipeline for synchronous Celery execution.

#     BUG 1 FIX: analysis_started / analysis_completed / analysis_failed
#     are now defined as local stub functions above (no external import needed).

#     BUG 2 FIX: Uses logger = logging.getLogger("tasks") defined at top of file.

#     BUG 3 FIX: local_plagiarism_score called WITHOUT await inside async function,
#     then wrapped with asyncio.to_thread() for non-blocking execution.
#     """
#     logger.info(
#         "Celery task received | task_id=%s doc_id=%d user_id=%s",
#         self.request.id, document_id, user_id,
#     )

#     # Increment active task counter
#     analysis_started()

#     try:
#         # Run the async pipeline in a fresh event loop (Celery worker is sync)
#         result = asyncio.run(_run_analysis_async(document_id, user_id, self))

#         # Record success
#         analysis_completed(result.get("processing_time", 0.0))

#         logger.info(
#             "Celery task SUCCESS | task_id=%s doc_id=%d",
#             self.request.id, document_id,
#         )

#         return result

#     except Exception as e:
#         # Record failure in metrics
#         analysis_failed()

#         logger.exception(
#             "Celery task FAILED | task_id=%s doc_id=%d error=%s",
#             self.request.id, document_id, str(e),
#         )

#         # Update Celery task state to FAILURE so frontend can detect it
#         self.update_state(
#             state="FAILURE",
#             meta={
#                 "progress": 0,
#                 "stage":    "Failed",
#                 "error":    str(e),
#             },
#         )

#         # Re-raise so Celery marks the task as failed in the result backend
#         raise









































































"""
Background analysis tasks — run asynchronously in Celery workers.

BUG FIXED IN THIS VERSION
──────────────────────────────────────────────────────────────────────
TypeError: '>' not supported between instances of 'coroutine' and 'float'

ROOT CAUSE:
  local_plagiarism_score() is declared as `async def` in plagiarism.py.

  The code was calling it like this:
      local_score = await asyncio.to_thread(local_plagiarism_score, text, other_texts)

  asyncio.to_thread(fn, *args) runs fn(*args) in a thread pool executor.
  When fn is an `async def`, calling fn(*args) in the thread returns a
  COROUTINE OBJECT — it does not execute the function, it does not await it.
  The coroutine is never run. local_score = <coroutine object at 0x...>.

  Later, compute_scores() tries: max(0.0, local_score)
  Python cannot compare a coroutine with a float → TypeError crash.

  The logger line before that also crashed:
      logger.info("...%.1f%%...", local_score, ...)
  → TypeError: must be real number, not coroutine

FIX:
  Since local_plagiarism_score IS async def, call it with await directly:
      local_score = await local_plagiarism_score(text, other_texts)

  asyncio.to_thread() is only for SYNC (non-async) functions.
  For async def functions: use await directly.

ALSO FIXED:
  asyncio.run() replaced with persistent event loop (loop.run_until_complete).
  asyncio.run() creates + destroys the event loop each task call, which
  corrupts asyncpg's internal pool state. A persistent loop prevents this.
──────────────────────────────────────────────────────────────────────
"""

import asyncio
import logging
import threading
from datetime import datetime
from typing import List, Optional

from app.core.celery_client import celery_app
from app.libs.database import db_service
from app.libs.google_search import google_search_with_matches
from app.libs.ai_detection import detect_ai_content_detailed
from app.libs.plagiarism import (
    local_plagiarism_score,
    local_plagiarism_score_with_commoncrawl,
)
from app.libs.models import AnalysisResult

# ── Logger ─────────────────────────────────────────────────────────────────────
logger = logging.getLogger("tasks")

# ── Configuration ──────────────────────────────────────────────────────────────
MIN_TEXT_LENGTH        = 20
SEARCH_TEXT_WORD_LIMIT = 300


# ── PERSISTENT EVENT LOOP — one per Celery worker process ─────────────────────
# Replaces asyncio.run() which creates + destroys a loop per task call.
# asyncpg pools are bound to the loop they were created on. If asyncio.run()
# destroys the loop, the pool becomes invalid and the next task hangs.
# A persistent loop lets asyncpg reuse the same healthy pool for all tasks.

_worker_loop: Optional[asyncio.AbstractEventLoop] = None
_loop_lock = threading.Lock()


def _get_worker_loop() -> asyncio.AbstractEventLoop:
    """Return the worker-process-persistent event loop, created once."""
    global _worker_loop
    if _worker_loop is not None and not _worker_loop.is_closed():
        return _worker_loop
    with _loop_lock:
        if _worker_loop is not None and not _worker_loop.is_closed():
            return _worker_loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        _worker_loop = loop
        logger.info("Celery worker: created persistent event loop id=%s", id(loop))
        return loop


# ── Task metrics ───────────────────────────────────────────────────────────────
_metrics = {"active": 0, "completed": 0, "failed": 0}


def analysis_started() -> None:
    _metrics["active"] += 1
    logger.info("Metrics | active=%d completed=%d failed=%d",
                _metrics["active"], _metrics["completed"], _metrics["failed"])


def analysis_completed(duration_s: float = 0.0) -> None:
    _metrics["active"]    = max(0, _metrics["active"] - 1)
    _metrics["completed"] += 1
    logger.info("Metrics | active=%d completed=%d failed=%d | duration=%.1fs",
                _metrics["active"], _metrics["completed"], _metrics["failed"], duration_s)


def analysis_failed() -> None:
    _metrics["active"] = max(0, _metrics["active"] - 1)
    _metrics["failed"] += 1
    logger.warning("Metrics | active=%d completed=%d failed=%d",
                   _metrics["active"], _metrics["completed"], _metrics["failed"])


# ── Helpers ────────────────────────────────────────────────────────────────────

def encode_web_source(url: str, match_pct: Optional[float] = None) -> str:
    if match_pct is not None:
        return f"web::{url}::{round(match_pct, 2)}"
    return f"web::{url}"


def compute_scores(
    verbatim_web_score: float,
    commoncrawl_score:  float,
    local_score:        float,
    ai_score:           float,
):
    plagiarism  = max(verbatim_web_score, commoncrawl_score * 0.5)
    plagiarism  = round(min(100.0, max(0.0, plagiarism)), 2)
    originality = round(max(0.0, 100.0 - plagiarism), 2)
    ai          = round(min(100.0, max(0.0, ai_score)), 2)
    internal    = round(min(100.0, max(0.0, local_score)), 2)
    return plagiarism, originality, ai, internal


def classify_submission(ai_pct: float, plagiarism_pct: float) -> dict:
    ai_high   = ai_pct >= 70
    ai_med    = 40 <= ai_pct < 70
    plag_high = plagiarism_pct >= 60
    plag_med  = 20 <= plagiarism_pct < 60

    if ai_high and plag_high:
        return {
            "case":        "Case 3 — AI Generated & Plagiarized",
            "verdict":     "AI-Generated AND Plagiarized",
            "description": (
                "Strong AI authorship signals combined with high verbatim web similarity. "
                "High probability this was generated by an AI tool using source "
                "material it was trained on or directly accessed."
            ),
            "risk":   "critical",
            "action": "Reject. Request original human-authored work with proper citations.",
        }
    if not ai_high and plag_high:
        return {
            "case":        "Case 1 — Human Plagiarism",
            "verdict":     "Human Plagiarism Detected",
            "description": (
                "Low AI probability with high verbatim web similarity. "
                "Content appears manually copied or paraphrased from existing "
                "sources without proper attribution."
            ),
            "risk":   "high",
            "action": "Reject. Request original work with citations for all borrowed content.",
        }
    if ai_high and not plag_high and not plag_med:
        return {
            "case":        "Case 2 — AI Generated (Original)",
            "verdict":     "AI-Generated Content — Not Copied",
            "description": (
                "High AI authorship probability. Content does not match known web "
                "sources — this appears to be original AI output, not copied from "
                "existing material."
            ),
            "risk":   "high",
            "action": "Review per institution AI policy. Original content but likely not student's own work.",
        }
    if not ai_high and not ai_med and not plag_high and not plag_med:
        return {
            "case":        "Case 4 — Human Original",
            "verdict":     "Likely Original Human Work",
            "description": (
                "Low AI probability and low verbatim web similarity. "
                "Content appears to be original human-authored work with no "
                "significant plagiarism concerns."
            ),
            "risk":   "low",
            "action": "Accept. No significant concerns detected.",
        }
    if ai_med and not plag_high:
        return {
            "case":        "Case 5 — Possible AI Assistance",
            "verdict":     "Possible AI Assistance Detected",
            "description": (
                "Moderate AI signals detected. Content may have been drafted or "
                "edited with AI assistance. Verbatim web plagiarism is not significant."
            ),
            "risk":   "medium",
            "action": (
                "Request student to confirm authorship. "
                "May be acceptable if institution permits AI assistance with disclosure."
            ),
        }
    if plag_med:
        return {
            "case":        "Case 6 — Moderate Similarity",
            "verdict":     f"Moderate Web Similarity{' + Possible AI Assistance' if ai_med else ''}",
            "description": (
                f"Moderate verbatim overlap with web sources"
                f"{' with possible AI assistance' if ai_med else ''}. "
                "Common in research-heavy work; review matched sources to confirm "
                "adequate citation of borrowed content."
            ),
            "risk":   "medium",
            "action": "Review matched sources. Verify all borrowed content is properly cited.",
        }
    return {
        "case":        "Inconclusive",
        "verdict":     "Manual Review Recommended",
        "description": "Mixed signals detected. Automated classification is inconclusive.",
        "risk":        "medium",
        "action":      "A human reviewer should assess this submission.",
    }


# ── Core async pipeline ────────────────────────────────────────────────────────

async def _run_analysis_async(document_id: int, user_id: str, task_self) -> dict:
    """
    Full analysis pipeline. Runs on the persistent worker event loop.

    ASYNC vs SYNC call rules applied here:
      local_plagiarism_score         → async def → use: await fn(args)
      local_plagiarism_score_with_commoncrawl → sync def → use: asyncio.to_thread(fn, args)
      google_search_with_matches     → sync def → use: asyncio.to_thread(fn, args)
      detect_ai_content_detailed     → sync def → use: asyncio.to_thread(fn, args)
      db_service methods             → async def → use: await fn(args)
    """
    import time as _time

    logger.info("[doc=%d] analysis_task_started", document_id)
    task_self.update_state(state="PROGRESS", meta={"progress": 10, "stage": "Loading document"})

    # ── Load document ──────────────────────────────────────────────────────────
    doc = await db_service.get_document(document_id)
    if not doc:
        raise ValueError(f"Document {document_id} not found in database")

    if doc["user_id"] != user_id:
        raise PermissionError(f"User {user_id} not authorized for document {document_id}")

    text = doc.get("extracted_text", "") or ""
    if len(text.strip()) < MIN_TEXT_LENGTH:
        raise ValueError(
            f"Insufficient text in document {document_id} "
            f"({len(text)} chars, minimum {MIN_TEXT_LENGTH})"
        )

    start = datetime.utcnow()

    # ── STAGE 1: Internal DB Similarity (20%) ─────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 20, "stage": "Checking internal database"})
    t1 = _time.perf_counter()

    others = await db_service.get_all_documents_texts(exclude_id=document_id)
    other_texts: List[str] = [
        (d.get("extracted_text") or d.get("text") or "")
        for d in others
        if (d.get("extracted_text") or d.get("text") or "").strip()
    ]

    local_score = 0.0
    try:
        # local_plagiarism_score IS async def → await it directly.
        # DO NOT use asyncio.to_thread() for async functions —
        # that would call the function in a thread returning a coroutine
        # object instead of executing it.
        local_score = await local_plagiarism_score(text, other_texts)
        logger.info(
            "[doc=%d] internal_db=%.1f%% docs=%d ms=%.0f",
            document_id, local_score, len(other_texts),
            (_time.perf_counter() - t1) * 1000,
        )
    except Exception as e:
        logger.exception("[doc=%d] internal_db_failed: %s", document_id, e)

    # ── STAGE 2: Verbatim Web Search (40%) ────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 40, "stage": "Searching web sources"})
    t2 = _time.perf_counter()

    verbatim_web_score = 0.0
    web_search_result  = {"urls": [], "matches": {}, "top_match_pct": 0.0, "queries_used": []}
    search_text        = " ".join(text.split()[:SEARCH_TEXT_WORD_LIMIT])

    try:
        # google_search_with_matches is sync def → wrap with asyncio.to_thread
        web_search_result  = await asyncio.to_thread(google_search_with_matches, search_text)
        verbatim_web_score = web_search_result.get("top_match_pct", 0.0)
        logger.info(
            "[doc=%d] web_search urls=%d top_match=%.1f%% ms=%.0f",
            document_id,
            len(web_search_result.get("urls", [])),
            verbatim_web_score,
            (_time.perf_counter() - t2) * 1000,
        )
    except Exception as e:
        logger.exception("[doc=%d] web_search_failed: %s", document_id, e)

    # ── STAGE 3: CommonCrawl (50%) ────────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 50, "stage": "Checking CommonCrawl"})
    t3 = _time.perf_counter()

    commoncrawl_score = 0.0
    try:
        # local_plagiarism_score_with_commoncrawl is sync def → asyncio.to_thread
        commoncrawl_score = await asyncio.to_thread(
            local_plagiarism_score_with_commoncrawl, text
        )
        logger.info(
            "[doc=%d] commoncrawl=%.1f%% ms=%.0f",
            document_id, commoncrawl_score, (_time.perf_counter() - t3) * 1000,
        )
    except Exception as e:
        logger.warning("[doc=%d] commoncrawl_failed: %s", document_id, e)

    # ── STAGE 4: AI Detection (70%) ───────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 70, "stage": "Detecting AI content"})
    t4 = _time.perf_counter()

    ai_score_raw = 0.0
    ai_detail    = {}
    try:
        # detect_ai_content_detailed is sync def → asyncio.to_thread
        ai_detail    = await asyncio.to_thread(detect_ai_content_detailed, text)
        ai_score_raw = float(ai_detail.get("score", 0.0))
        ai_score_raw = min(100.0, max(0.0, ai_score_raw))
        logger.info(
            "[doc=%d] ai=%.1f%% academic=%s model=%s "
            "roberta=%.0f%% ppl=%.0f%% burst=%.0f%% "
            "style=%.0f%% tokdist=%.0f%% patterns=%.0f%% ms=%.0f",
            document_id,
            ai_score_raw,
            ai_detail.get("is_academic", False),
            ai_detail.get("likely_model") or "unknown",
            ai_detail.get("breakdown", {}).get("roberta", 0),
            ai_detail.get("breakdown", {}).get("perplexity", 0),
            ai_detail.get("breakdown", {}).get("burstiness", 0),
            ai_detail.get("breakdown", {}).get("stylometrics", 0),
            ai_detail.get("breakdown", {}).get("token_dist", 0),
            ai_detail.get("breakdown", {}).get("ai_patterns", 0),
            (_time.perf_counter() - t4) * 1000,
        )
    except Exception as e:
        logger.exception("[doc=%d] ai_detection_failed: %s", document_id, e)

    # ── STAGE 5: Compute Scores (80%) ─────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 80, "stage": "Computing final scores"})

    plagiarism_score, originality_score, ai_score, internal_score = compute_scores(
        verbatim_web_score = verbatim_web_score,
        commoncrawl_score  = commoncrawl_score,
        local_score        = local_score,
        ai_score           = ai_score_raw,
    )

    interpretation = classify_submission(ai_score, plagiarism_score)

    # ── STAGE 6: Build Sources List (90%) ─────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 90, "stage": "Finalizing results"})

    sources: List[str] = []
    for url in web_search_result.get("urls", []):
        m = web_search_result.get("matches", {}).get(url, {})
        sources.append(encode_web_source(url, m.get("match_pct")))

    if local_score > 15:
        sources.append(f"local_db::document:{document_id}")

    sources = list(dict.fromkeys(sources))  # Deduplicate, preserve order

    end             = datetime.utcnow()
    processing_time = (end - start).total_seconds()

    # ── STAGE 7: Write to DB (95%) ────────────────────────────────────────────
    result_obj = AnalysisResult(
        document_id                 = document_id,
        analyzed_by                 = user_id,
        ai_detected_percentage      = ai_score,
        web_source_percentage       = plagiarism_score,
        local_similarity_percentage = internal_score,
        human_written_percentage    = originality_score,
        analysis_summary            = interpretation["verdict"],
        analysis_date               = end,
        matched_web_sources         = sources,
        processing_time_seconds     = processing_time,
    )

    await db_service.create_analysis_result(result_obj)

    logger.info(
        "[doc=%d] analysis_complete | %s | risk=%s | "
        "ai=%.1f%% plag=%.1f%% orig=%.1f%% internal=%.1f%% | "
        "sources=%d duration=%.2fs",
        document_id,
        interpretation["case"], interpretation["risk"],
        ai_score, plagiarism_score, originality_score, internal_score,
        len(sources), processing_time,
    )

    return {
        "document_id": document_id,
        "status":      "completed",
        "scores": {
            "ai":          ai_score,
            "plagiarism":  plagiarism_score,
            "originality": originality_score,
            "internal":    internal_score,
        },
        "processing_time": processing_time,
    }


# ── Celery task ────────────────────────────────────────────────────────────────

@celery_app.task(bind=True, name="run_analysis")
def run_analysis(self, document_id: int, user_id: str):
    """
    Celery task wrapper. Uses a persistent event loop instead of asyncio.run().

    asyncio.run() creates and destroys an event loop per task call.
    asyncpg pools are bound to the loop they were created on — destroying
    the loop corrupts the pool. Subsequent tasks hang waiting on invalid fds.

    loop.run_until_complete() on a persistent loop prevents this entirely.
    """
    logger.info("Task received | task_id=%s doc_id=%d user=%s",
                self.request.id, document_id, user_id)

    analysis_started()

    try:
        loop   = _get_worker_loop()
        result = loop.run_until_complete(
            _run_analysis_async(document_id, user_id, self)
        )

        analysis_completed(result.get("processing_time", 0.0))
        logger.info("Task SUCCESS | task_id=%s doc_id=%d scores=%s",
                    self.request.id, document_id, result.get("scores", {}))
        return result

    except Exception as e:
        analysis_failed()
        logger.exception("Task FAILED | task_id=%s doc_id=%d error=%s",
                         self.request.id, document_id, str(e))
        self.update_state(
            state="FAILURE",
            meta={"progress": 0, "stage": "Failed", "error": str(e)},
        )
        raise