"""
Background analysis tasks — run asynchronously in Celery workers.

Observability changes (M6):
  - structlog replaces plain logging.getLogger → every log line is JSON
  - correlation_id / task_id / doc_id bound via structlog.contextvars so
    ALL lines from one task share the same IDs (traceable in Azure Log Analytics)
  - analysis_started / analysis_completed / analysis_failed update the
    in-memory metrics store that /api/metrics reads
  - Canonical completion log:
      log.info("analysis_complete",
               doc_id=..., ai=..., web=..., orig=..., internal=...,
               sources=..., duration_s=..., case=...)
"""

import asyncio
import uuid
from datetime import datetime
from typing import List, Optional

import structlog

from app.core.celery_client import celery_app
# from app.core.metrics import analysis_started, analysis_completed, analysis_failed
from app.libs.database import db_service
from app.libs.extract import extract_text
from app.libs.google_search import google_search_with_matches
from app.libs.ai_detection import detect_ai_content_detailed
from app.libs.plagiarism import (
    local_plagiarism_score,
    local_plagiarism_score_with_commoncrawl,
)
from app.libs.models import AnalysisResult

# ── Logging setup — runs once when the Celery worker imports this module ───────
# configure_logging() initialises structlog + stdlib root handler with JSON output.
# This call is safe even if main.py already called it (idempotent handler swap).
# from app.libs.logger import configure_logging, get_logger

# configure_logging()
# log = get_logger("tasks")

# ── Configuration (same as main.py) ───────────────────────────────────────────
MIN_TEXT_LENGTH = 20
SEARCH_TEXT_WORD_LIMIT = 300


# ── Helpers (duplicated from main.py to keep workers self-contained) ──────────

def encode_web_source(url: str, match_pct: Optional[float] = None) -> str:
    """Encode a web source URL (with optional match%) as a DB-safe string."""
    if match_pct is not None:
        return f"web::{url}::{round(match_pct, 2)}"
    return f"web::{url}"


def compute_scores(
    verbatim_web_score: float,
    commoncrawl_score: float,
    local_score: float,
    ai_score: float,
):
    """Compute final scores from raw analysis signals."""
    plagiarism = max(verbatim_web_score, commoncrawl_score * 0.5)
    plagiarism = round(min(100.0, max(0.0, plagiarism)), 2)
    originality = round(max(0.0, 100.0 - plagiarism), 2)
    ai = round(min(100.0, max(0.0, ai_score)), 2)
    internal = round(min(100.0, max(0.0, local_score)), 2)
    return plagiarism, originality, ai, internal


def classify_submission(ai_pct: float, plagiarism_pct: float) -> dict:
    """Map (AI%, Plagiarism%) to interpretation case."""
    ai_high = ai_pct >= 70
    ai_med = 40 <= ai_pct < 70
    plag_high = plagiarism_pct >= 60
    plag_med = 20 <= plagiarism_pct < 60

    if ai_high and plag_high:
        return {
            "case": "Case 3 — AI Generated & Plagiarized",
            "verdict": "AI-Generated AND Plagiarized",
            "description": (
                "Strong AI authorship signals combined with high verbatim web similarity. "
                "High probability this was generated by an AI tool using source "
                "material it was trained on or directly accessed."
            ),
            "risk": "critical",
            "action": "Reject. Request original human-authored work with proper citations.",
        }

    if not ai_high and plag_high:
        return {
            "case": "Case 1 — Human Plagiarism",
            "verdict": "Human Plagiarism Detected",
            "description": (
                "Low AI probability with high verbatim web similarity. "
                "Content appears manually copied or paraphrased from existing "
                "sources without proper attribution."
            ),
            "risk": "high",
            "action": "Reject. Request original work with citations for all borrowed content.",
        }

    if ai_high and not plag_high and not plag_med:
        return {
            "case": "Case 2 — AI Generated (Original)",
            "verdict": "AI-Generated Content — Not Copied",
            "description": (
                "High AI authorship probability. Content does not match known web "
                "sources — this appears to be original AI output, not copied from "
                "existing material."
            ),
            "risk": "high",
            "action": "Review per institution AI policy. Original content but likely not student's own work.",
        }

    if not ai_high and not ai_med and not plag_high and not plag_med:
        return {
            "case": "Case 4 — Human Original",
            "verdict": "Likely Original Human Work",
            "description": (
                "Low AI probability and low verbatim web similarity. "
                "Content appears to be original human-authored work with no "
                "significant plagiarism concerns."
            ),
            "risk": "low",
            "action": "Accept. No significant concerns detected.",
        }

    if ai_med and not plag_high:
        return {
            "case": "Case 5 — Possible AI Assistance",
            "verdict": "Possible AI Assistance Detected",
            "description": (
                "Moderate AI signals detected. Content may have been drafted or "
                "edited with AI assistance. Verbatim web plagiarism is not significant."
            ),
            "risk": "medium",
            "action": (
                "Request student to confirm authorship. "
                "May be acceptable if institution permits AI assistance with disclosure."
            ),
        }

    if plag_med:
        return {
            "case": "Case 6 — Moderate Similarity",
            "verdict": f"Moderate Web Similarity{' + Possible AI Assistance' if ai_med else ''}",
            "description": (
                f"Moderate verbatim overlap with web sources"
                f"{' with possible AI assistance' if ai_med else ''}. "
                "Common in research-heavy work; review matched sources to confirm "
                "adequate citation of borrowed content."
            ),
            "risk": "medium",
            "action": "Review matched sources. Verify all borrowed content is properly cited.",
        }

    return {
        "case": "Inconclusive",
        "verdict": "Manual Review Recommended",
        "description": "Mixed signals detected. Automated classification is inconclusive.",
        "risk": "medium",
        "action": "A human reviewer should assess this submission.",
    }


# ── Core async logic ───────────────────────────────────────────────────────────

async def _run_analysis_async(document_id: int, user_id: str, task_self):
    """
    ✅ ASYNC CORE LOGIC — separated from Celery task decorator.
    This allows proper async/await handling without event loop issues.

    Observability:
      - structlog.contextvars carries task_id + doc_id on every log line
      - Timing captured at each stage and reported in the canonical completion log
      - Metrics counters updated via analysis_started / analysis_completed / analysis_failed
    """
    import time as _time

    # ── Bind task-scoped context so every log line carries these fields ────────
    structlog.contextvars.bind_contextvars(
        task_id=task_self.request.id,
        doc_id=document_id,
        user_id=user_id,
    )

    log.info("analysis_task_started", stage="load_document")
    task_self.update_state(state="PROGRESS", meta={"progress": 10, "stage": "Loading document"})

    # ── Load document ──────────────────────────────────────────────────────────
    t_start = _time.perf_counter()

    doc = await db_service.get_document(document_id)
    if not doc:
        raise ValueError(f"Document {document_id} not found")

    if doc["user_id"] != user_id:
        raise PermissionError(f"User {user_id} not authorized for document {document_id}")

    text = doc.get("extracted_text", "") or ""
    if len(text.strip()) < MIN_TEXT_LENGTH:
        raise ValueError(f"Insufficient text extracted ({len(text)} chars)")

    start = datetime.utcnow()

    # ── 1. INTERNAL DB SIMILARITY (20%) ───────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 20, "stage": "Checking internal DB"})
    t1 = _time.perf_counter()

    others = await db_service.get_all_documents_texts(exclude_id=document_id)
    other_texts: List[str] = [
        (d.get("extracted_text") or d.get("text") or "")
        for d in others
        if (d.get("extracted_text") or d.get("text") or "").strip()
    ]

    local_score = 0.0
    try:
        local_score = await local_plagiarism_score(text, other_texts)
        log.info(
            "internal_db_similarity_done",
            internal_score=round(local_score, 1),
            compared_docs=len(other_texts),
            stage_ms=round((_time.perf_counter() - t1) * 1000, 1),
        )
    except Exception as e:
        log.exception("internal_db_similarity_failed", error=str(e))

    # ── 2. VERBATIM WEB SEARCH (40%) ──────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 40, "stage": "Searching web"})
    t2 = _time.perf_counter()

    verbatim_web_score = 0.0
    web_search_result = {
        "urls": [],
        "matches": {},
        "top_match_pct": 0.0,
        "queries_used": [],
    }

    search_text = " ".join(text.split()[:SEARCH_TEXT_WORD_LIMIT])

    try:
        web_search_result = google_search_with_matches(search_text)
        verbatim_web_score = web_search_result.get("top_match_pct", 0.0)
        found_urls = web_search_result.get("urls", [])
        log.info(
            "web_search_done",
            urls_found=len(found_urls),
            top_match_pct=round(verbatim_web_score, 1),
            stage_ms=round((_time.perf_counter() - t2) * 1000, 1),
        )
    except Exception as e:
        log.exception("web_search_failed", error=str(e))

    # ── 3. COMMONCRAWL (50%) ──────────────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 50, "stage": "Checking CommonCrawl"})
    t3 = _time.perf_counter()

    commoncrawl_score = 0.0
    try:
        commoncrawl_score = local_plagiarism_score_with_commoncrawl(text)
        log.info(
            "commoncrawl_done",
            score=round(commoncrawl_score, 1),
            stage_ms=round((_time.perf_counter() - t3) * 1000, 1),
        )
    except Exception as e:
        log.warning("commoncrawl_failed", error=str(e))

    # ── 4. AI DETECTION (70%) ─────────────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 70, "stage": "Detecting AI"})
    t4 = _time.perf_counter()

    ai_score_raw = 0.0
    ai_detail = {}
    try:
        ai_detail = detect_ai_content_detailed(text)
        ai_score_raw = float(ai_detail.get("score", 0.0))
        ai_score_raw = min(100.0, max(0.0, ai_score_raw))
        log.info(
            "ai_detection_done",
            ai_score=round(ai_score_raw, 1),
            is_academic=ai_detail.get("is_academic", False),
            stage_ms=round((_time.perf_counter() - t4) * 1000, 1),
        )
    except Exception as e:
        log.exception("ai_detection_failed", error=str(e))

    # ── 5. COMPUTE SCORES (80%) ───────────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 80, "stage": "Computing scores"})

    plagiarism_score, originality_score, ai_score, internal_score = compute_scores(
        verbatim_web_score=verbatim_web_score,
        commoncrawl_score=commoncrawl_score,
        local_score=local_score,
        ai_score=ai_score_raw,
    )

    interpretation = classify_submission(ai_score, plagiarism_score)

    # ── 6. BUILD SOURCES LIST (90%) ───────────────────────────────────────────
    task_self.update_state(state="PROGRESS", meta={"progress": 90, "stage": "Finalizing results"})

    sources: List[str] = []
    found_urls = web_search_result.get("urls", [])
    url_matches = web_search_result.get("matches", {})

    for url in found_urls:
        m = url_matches.get(url, {})
        match_pct = m.get("match_pct")
        sources.append(encode_web_source(url, match_pct))

    if local_score > 15:
        sources.append(f"local_db::document:{document_id}")

    sources = list(dict.fromkeys(sources))  # Deduplicate

    end = datetime.utcnow()
    processing_time = (end - start).total_seconds()

    # ── 7. STORE RESULT (95%) ─────────────────────────────────────────────────
    result = AnalysisResult(
        document_id=document_id,
        analyzed_by=user_id,
        ai_detected_percentage=ai_score,
        web_source_percentage=plagiarism_score,
        local_similarity_percentage=internal_score,
        human_written_percentage=originality_score,
        analysis_summary=interpretation["verdict"],
        analysis_date=end,
        matched_web_sources=sources,
        processing_time_seconds=processing_time,
    )

    await db_service.create_analysis_result(result)

    # ── Canonical completion log (queryable in Azure Log Analytics) ───────────
    log.info(
        "analysis_complete",
        doc_id=document_id,
        ai=ai_score,
        web=plagiarism_score,
        orig=originality_score,
        internal=internal_score,
        sources=len(sources),
        duration_s=round(processing_time, 2),
        case=interpretation["case"],
        risk=interpretation["risk"],
    )

    task_self.update_state(state="SUCCESS", meta={"progress": 100, "stage": "Complete"})

    return {
        "document_id": document_id,
        "status": "completed",
        "scores": {
            "ai": ai_score,
            "plagiarism": plagiarism_score,
            "originality": originality_score,
            "internal": internal_score,
        },
        "processing_time": processing_time,
    }


# ── Celery task wrapper ────────────────────────────────────────────────────────

@celery_app.task(bind=True, name="run_analysis")
def run_analysis(self, document_id: int, user_id: str):
    """
    Celery task wrapper — handles async execution cleanly.

    Lifecycle hooks:
      analysis_started()   → increments active counter in metrics store
      analysis_completed() → decrements active, increments done, records duration
      analysis_failed()    → decrements active, increments error counter
    """
    analysis_started()
    try:
        result = asyncio.run(_run_analysis_async(document_id, user_id, self))
        analysis_completed(result.get("processing_time", 0.0))
        return result

    except Exception as e:
        analysis_failed()
        log.exception(
            "analysis_task_failed",
            task_id=self.request.id,
            doc_id=document_id,
            error=str(e),
        )
        self.update_state(
            state="FAILURE",
            meta={
                "progress": 0,
                "error": str(e),
            },
        )
        raise
    finally:
        # Always clear contextvars so the next task on this worker starts clean
        structlog.contextvars.clear_contextvars()
